[tasks.dev]
desc = "Run the MCP server in development mode"
cmds = ["npm run dev"]

[tasks.deps]
cmds = ["npm i"]

[tasks.build]
desc = "Build the project"
deps = [["deps"]]
cmds = ["npm run build"]

#
# test
#
[tasks.test]
cmds = ["npm run test"]

[tasks."test:demo"]
cmds = ["npm run demo"]

[tasks."test:fetch"]
cmds = ["npm run test:fetch"]

[tasks."test:all"]
deps = [["test"], ["test:demo"], ["test:fetch"]]
cmds = ["echo Done!"]

#
# lint
# 
[tasks."lint:check"]
desc = "check files"
cmds = ["npx prettier --check ."]

[tasks."lint:fix"]
desc = "fix files"
cmds = ["npx prettier --write ."]
